# Generated by Django 4.1.2 on 2022-10-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(default='', upload_to='feed_images/'),
        ),
    ]
