# Generated by Django 4.1.2 on 2022-10-20 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
